version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16

    working_directory: ~/client

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      deploy:
        machine:
          enabled: true

        working_directory: ~/client

        steps:
          - add_ssh_keys:
              fingerprints:
                - "07:06:de:31:28:a1:f4:14:ef:74:b8:3b:b3:33:f1:d4"
          - checkout
          - run:
              name: Push Main to Production
              command: |
                git push https://github.com/JoshuaRully/weather-app.git main:production
    
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: production
      - deploy:
          filters:
            branches:
              ignore: production
          requires:
            - build